package a.entity.gus06.sys.expression1.apply.opmap.e_e;

import a.framework.*;
import java.util.Map;
import java.util.HashMap;

public class EntityImpl implements Entity, G {

	public String creationDate() {return "20250321";}





	private Map map;

	public EntityImpl() throws Exception
	{
		map = new HashMap();
		
		put("_e0",		Outside.service(this,"gus06.sys.expression1.apply.op._e0"));
		put("_e_add",		Outside.service(this,"gus06.sys.expression1.apply.op._e_add"));
		put("_e_add0",		Outside.service(this,"gus06.sys.expression1.apply.op._e_add0"));
		put("_e_add0_ig",	Outside.service(this,"gus06.sys.expression1.apply.op._e_add0_ig"));
		put("_e_add0_ig_d",	Outside.service(this,"gus06.sys.expression1.apply.op._e_add0_ig_d"));
		put("_e_add0_y",	Outside.service(this,"gus06.sys.expression1.apply.op._e_add0_y"));
		put("_e_add_ct",	Outside.service(this,"gus06.sys.expression1.apply.op._e_add_ct"));
		put("_e_add_ig",	Outside.service(this,"gus06.sys.expression1.apply.op._e_add_ig"));
		put("_e_add_ig_d",	Outside.service(this,"gus06.sys.expression1.apply.op._e_add_ig_d"));
		put("_e_addall",	Outside.service(this,"gus06.sys.expression1.apply.op._e_addall"));
		put("_e_addall0",	Outside.service(this,"gus06.sys.expression1.apply.op._e_addall0"));
		put("_e_addall0_ct",	Outside.service(this,"gus06.sys.expression1.apply.op._e_addall0_ct"));
		put("_e_addall0_ig",	Outside.service(this,"gus06.sys.expression1.apply.op._e_addall0_ig"));
		put("_e_addall0_ig_d",	Outside.service(this,"gus06.sys.expression1.apply.op._e_addall0_ig_d"));
		put("_e_addall_ct",	Outside.service(this,"gus06.sys.expression1.apply.op._e_addall_ct"));
		put("_e_addall_ig",	Outside.service(this,"gus06.sys.expression1.apply.op._e_addall_ig"));
		put("_e_addall_ig_d",	Outside.service(this,"gus06.sys.expression1.apply.op._e_addall_ig_d"));
		put("_e_backupfile",	Outside.service(this,"gus06.sys.expression1.apply.op._e_backupfile"));
		put("_e_backupfile_changed",	Outside.service(this,"gus06.sys.expression1.apply.op._e_backupfile_changed"));
		put("_e_backupfile_daily",	Outside.service(this,"gus06.sys.expression1.apply.op._e_backupfile_daily"));
		put("_e_backupfile_monthly",	Outside.service(this,"gus06.sys.expression1.apply.op._e_backupfile_monthly"));
		put("_e_backupfile_yearly",	Outside.service(this,"gus06.sys.expression1.apply.op._e_backupfile_yearly"));
		put("_e_beep",		Outside.service(this,"gus06.sys.expression1.apply.op._e_beep"));
		put("_e_beeps",		Outside.service(this,"gus06.sys.expression1.apply.op._e_beeps"));
		put("_e_browse",	Outside.service(this,"gus06.sys.expression1.apply.op._e_browse"));
		put("_e_changefile",	Outside.service(this,"gus06.sys.expression1.apply.op._e_changefile"));
		put("_e_changekey",	Outside.service(this,"gus06.sys.expression1.apply.op._e_changekey"));
		put("_e_changekey_ct",	Outside.service(this,"gus06.sys.expression1.apply.op._e_changekey_ct"));
		put("_e_changekey_full",Outside.service(this,"gus06.sys.expression1.apply.op._e_changekey_full"));
		put("_e_chk_empty",	Outside.service(this,"gus06.sys.expression1.apply.op._e_chk_empty"));
		put("_e_chk_eq",	Outside.service(this,"gus06.sys.expression1.apply.op._e_chk_eq"));
		put("_e_chk_false",	Outside.service(this,"gus06.sys.expression1.apply.op._e_chk_false"));
		put("_e_chk_nempty",	Outside.service(this,"gus06.sys.expression1.apply.op._e_chk_nempty"));
		put("_e_chk_neq",	Outside.service(this,"gus06.sys.expression1.apply.op._e_chk_neq"));
		put("_e_chk_nnull",	Outside.service(this,"gus06.sys.expression1.apply.op._e_chk_nnull"));
		put("_e_chk_null",	Outside.service(this,"gus06.sys.expression1.apply.op._e_chk_null"));
		put("_e_chk_size",	Outside.service(this,"gus06.sys.expression1.apply.op._e_chk_size"));
		put("_e_chk_true",	Outside.service(this,"gus06.sys.expression1.apply.op._e_chk_true"));
		put("_e_clean",		Outside.service(this,"gus06.sys.expression1.apply.op._e_clean"));
		put("_e_clipboard",	Outside.service(this,"gus06.sys.expression1.apply.op._e_clipboard"));
		put("_e_clipboard_queue",Outside.service(this,"gus06.sys.expression1.apply.op._e_clipboard_queue"));
		put("_e_clipboard_queue2",Outside.service(this,"gus06.sys.expression1.apply.op._e_clipboard_queue2"));
		put("_e_close",		Outside.service(this,"gus06.sys.expression1.apply.op._e_close"));
		put("_e_collect",	Outside.service(this,"gus06.sys.expression1.apply.op._e_collect"));
		put("_e_collect2",	Outside.service(this,"gus06.sys.expression1.apply.op._e_collect2"));
		put("_e_collect3",	Outside.service(this,"gus06.sys.expression1.apply.op._e_collect3"));
		put("_e_collect_w",	Outside.service(this,"gus06.sys.expression1.apply.op._e_collect_w"));
		put("_e_collectkey",	Outside.service(this,"gus06.sys.expression1.apply.op._e_collectkey"));
		put("_e_collectkey2",	Outside.service(this,"gus06.sys.expression1.apply.op._e_collectkey2"));
		put("_e_collectkey3",	Outside.service(this,"gus06.sys.expression1.apply.op._e_collectkey3"));
		put("_e_collectkey_w",	Outside.service(this,"gus06.sys.expression1.apply.op._e_collectkey_w"));
		put("_e_collectline",	Outside.service(this,"gus06.sys.expression1.apply.op._e_collectline"));
		put("_e_collectline_w",	Outside.service(this,"gus06.sys.expression1.apply.op._e_collectline_w"));
		put("_e_collectvalue",	Outside.service(this,"gus06.sys.expression1.apply.op._e_collectvalue"));
		put("_e_collectvalue2",	Outside.service(this,"gus06.sys.expression1.apply.op._e_collectvalue2"));
		put("_e_collectvalue3",	Outside.service(this,"gus06.sys.expression1.apply.op._e_collectvalue3"));
		put("_e_collectvalue_w",Outside.service(this,"gus06.sys.expression1.apply.op._e_collectvalue_w"));
		put("_e_complete",	Outside.service(this,"gus06.sys.expression1.apply.op._e_complete"));
		put("_e_complete2",	Outside.service(this,"gus06.sys.expression1.apply.op._e_complete2"));
		put("_e_completeall",	Outside.service(this,"gus06.sys.expression1.apply.op._e_completeall"));
		put("_e_completeall2",	Outside.service(this,"gus06.sys.expression1.apply.op._e_completeall2"));
		put("_e_convert",	Outside.service(this,"gus06.sys.expression1.apply.op._e_convert"));
		put("_e_copy",		Outside.service(this,"gus06.sys.expression1.apply.op._e_copy"));
		put("_e_copydown",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copydown"));
		put("_e_copydir",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copydir"));
		put("_e_copydir1",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copydir1"));
		put("_e_copydir1_au",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copydir1_au"));
		put("_e_copydir1_ig",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copydir1_ig"));
		put("_e_copydir1_re",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copydir1_re"));
		put("_e_copydir_au",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copydir_au"));
		put("_e_copydir_ig",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copydir_ig"));
		put("_e_copydir_re",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copydir_re"));
		put("_e_copyfile",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copyfile"));
		put("_e_copyfile_au",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copyfile_au"));
		put("_e_copyfile_ig",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copyfile_ig"));
		put("_e_copyfile_inside",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copyfile_inside"));
		put("_e_copyfile_inside_timestamped",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copyfile_inside_timestamped"));
		put("_e_copyfile_re",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copyfile_re"));
		put("_e_copyfile_sync_date",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copyfile_sync_date"));
		put("_e_copyup",	Outside.service(this,"gus06.sys.expression1.apply.op._e_copyup"));
		put("_e_createfile",	Outside.service(this,"gus06.sys.expression1.apply.op._e_createfile"));
		put("_e_createfile_ow",	Outside.service(this,"gus06.sys.expression1.apply.op._e_createfile_ow"));
		put("_e_createdir",	Outside.service(this,"gus06.sys.expression1.apply.op._e_createdir"));
		put("_e_delete",	Outside.service(this,"gus06.sys.expression1.apply.op._e_delete"));
		put("_e_delete_ifempty",Outside.service(this,"gus06.sys.expression1.apply.op._e_delete_ifempty"));
		put("_e_download",	Outside.service(this,"gus06.sys.expression1.apply.op._e_download"));
		put("_e_duplicatekey",	Outside.service(this,"gus06.sys.expression1.apply.op._e_duplicatekey"));
		put("_e_duplicatekey_full",	Outside.service(this,"gus06.sys.expression1.apply.op._e_duplicatekey_full"));
		put("_e_each",		Outside.service(this,"gus06.sys.expression1.apply.op._e_each"));
		put("_e_each_w",	Outside.service(this,"gus06.sys.expression1.apply.op._e_each_w"));
		put("_e_eachkey",	Outside.service(this,"gus06.sys.expression1.apply.op._e_eachkey"));
		put("_e_eachkey_w",	Outside.service(this,"gus06.sys.expression1.apply.op._e_eachkey_w"));
		put("_e_eachvalue",	Outside.service(this,"gus06.sys.expression1.apply.op._e_eachvalue"));
		put("_e_eachvalue_w",	Outside.service(this,"gus06.sys.expression1.apply.op._e_eachvalue_w"));
		put("_e_eee",		Outside.service(this,"gus06.sys.expression1.apply.op._e_eee"));
		put("_e_empty",		Outside.service(this,"gus06.sys.expression1.apply.op._e_empty"));
		put("_e_exec",		Outside.service(this,"gus06.sys.expression1.apply.op._e_exec"));
		put("_e_exec_as_batch",	Outside.service(this,"gus06.sys.expression1.apply.op._e_exec_as_batch"));
		put("_e_initdir",	Outside.service(this,"gus06.sys.expression1.apply.op._e_initdir"));
		put("_e_initfile",	Outside.service(this,"gus06.sys.expression1.apply.op._e_initfile"));
		put("_e_initsyserr",	Outside.service(this,"gus06.sys.expression1.apply.op._e_initsyserr"));
		put("_e_initsysout",	Outside.service(this,"gus06.sys.expression1.apply.op._e_initsysout"));
		put("_e_insert",	Outside.service(this,"gus06.sys.expression1.apply.op._e_insert"));
		put("_e_insertall",	Outside.service(this,"gus06.sys.expression1.apply.op._e_insertall"));
		put("_e_invertfile",	Outside.service(this,"gus06.sys.expression1.apply.op._e_invertfile"));
		put("_e_keep",		Outside.service(this,"gus06.sys.expression1.apply.op._e_keep"));
		put("_e_keepall",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall"));
		put("_e_keepall_co",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_co"));
		put("_e_keepall_co_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_co_i"));
		put("_e_keepall_co_n",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_co_n"));
		put("_e_keepall_eq",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_eq"));
		put("_e_keepall_eq_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_eq_i"));
		put("_e_keepall_eq_n",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_eq_n"));
		put("_e_keepall_en",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_en"));
		put("_e_keepall_en_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_en_i"));
		put("_e_keepall_en_n",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_en_n"));
		put("_e_keepall_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_i"));
		put("_e_keepall_k",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_k"));
		put("_e_keepall_kco",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_kco"));
		put("_e_keepall_kco_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_kco_i"));
		put("_e_keepall_kco_n",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_kco_n"));
		put("_e_keepall_keq",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_keq"));
		put("_e_keepall_keq_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_keq_i"));
		put("_e_keepall_keq_n",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_keq_n"));
		put("_e_keepall_ken",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_ken"));
		put("_e_keepall_ken_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_ken_i"));
		put("_e_keepall_ken_n",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_ken_n"));
		put("_e_keepall_kst",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_kst"));
		put("_e_keepall_kst_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_kst_i"));
		put("_e_keepall_kst_n",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_kst_n"));
		put("_e_keepall_n",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_n"));
		put("_e_keepall_nempty",Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_nempty"));
		put("_e_keepall_nnull",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_nnull"));
		put("_e_keepall_st",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_st"));
		put("_e_keepall_st_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_st_i"));
		put("_e_keepall_st_n",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_st_n"));
		put("_e_keepall_v",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_v"));
		put("_e_keepall_vco",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_vco"));
		put("_e_keepall_vco_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_vco_i"));
		put("_e_keepall_vco_n",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_vco_n"));
		put("_e_keepall_veq",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_veq"));
		put("_e_keepall_veq_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_veq_i"));
		put("_e_keepall_veq_n",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_veq_n"));
		put("_e_keepall_ven",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_ven"));
		put("_e_keepall_ven_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_ven_i"));
		put("_e_keepall_ven_n",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_ven_n"));
		put("_e_keepall_vst",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_vst"));
		put("_e_keepall_vst_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_vst_i"));
		put("_e_keepall_vst_n",	Outside.service(this,"gus06.sys.expression1.apply.op._e_keepall_vst_n"));
		put("_e_locate",	Outside.service(this,"gus06.sys.expression1.apply.op._e_locate"));
		put("_e_mouse_clickleft",	Outside.service(this,"gus06.sys.expression1.apply.op._e_mouse_clickleft"));
		put("_e_mouse_clickleft2",	Outside.service(this,"gus06.sys.expression1.apply.op._e_mouse_clickleft2"));
		put("_e_mouse_clickright",	Outside.service(this,"gus06.sys.expression1.apply.op._e_mouse_clickright"));
		put("_e_mouse_clickright2",	Outside.service(this,"gus06.sys.expression1.apply.op._e_mouse_clickright2"));
		put("_e_mouse_move",		Outside.service(this,"gus06.sys.expression1.apply.op._e_mouse_move"));
		put("_e_mouse_pos",		Outside.service(this,"gus06.sys.expression1.apply.op._e_mouse_pos"));
		put("_e_mouse_pressleft",	Outside.service(this,"gus06.sys.expression1.apply.op._e_mouse_pressleft"));
		put("_e_mouse_pressright",	Outside.service(this,"gus06.sys.expression1.apply.op._e_mouse_pressright"));
		put("_e_mouse_releaseleft",	Outside.service(this,"gus06.sys.expression1.apply.op._e_mouse_releaseleft"));
		put("_e_mouse_releaseright",	Outside.service(this,"gus06.sys.expression1.apply.op._e_mouse_releaseright"));
		put("_e_movedir",	Outside.service(this,"gus06.sys.expression1.apply.op._e_movedir"));
		put("_e_movedir_au",	Outside.service(this,"gus06.sys.expression1.apply.op._e_movedir_au"));
		put("_e_movedir_ig",	Outside.service(this,"gus06.sys.expression1.apply.op._e_movedir_ig"));
		put("_e_movedir_re",	Outside.service(this,"gus06.sys.expression1.apply.op._e_movedir_re"));
		put("_e_movedown",	Outside.service(this,"gus06.sys.expression1.apply.op._e_movedown"));
		put("_e_movefile",	Outside.service(this,"gus06.sys.expression1.apply.op._e_movefile"));
		put("_e_movefile_inside",	Outside.service(this,"gus06.sys.expression1.apply.op._e_movefile_inside"));
		put("_e_movefile_inside_timestamped",	Outside.service(this,"gus06.sys.expression1.apply.op._e_movefile_inside_timestamped"));
		put("_e_movefile_au",	Outside.service(this,"gus06.sys.expression1.apply.op._e_movefile_au"));
		put("_e_movefile_ig",	Outside.service(this,"gus06.sys.expression1.apply.op._e_movefile_ig"));
		put("_e_movefile_in",	Outside.service(this,"gus06.sys.expression1.apply.op._e_movefile_in"));
		put("_e_movefile_re",	Outside.service(this,"gus06.sys.expression1.apply.op._e_movefile_re"));
		put("_e_moveup",	Outside.service(this,"gus06.sys.expression1.apply.op._e_moveup"));
		put("_e_open",		Outside.service(this,"gus06.sys.expression1.apply.op._e_open"));
		put("_e_open_as_batch",	Outside.service(this,"gus06.sys.expression1.apply.op._e_open_as_batch"));
		put("_e_play",		Outside.service(this,"gus06.sys.expression1.apply.op._e_play"));
		put("_e_permute",	Outside.service(this,"gus06.sys.expression1.apply.op._e_permute"));
		put("_e_permute_inv",	Outside.service(this,"gus06.sys.expression1.apply.op._e_permute_inv"));
		put("_e_print",		Outside.service(this,"gus06.sys.expression1.apply.op._e_print"));
		put("_e_println",	Outside.service(this,"gus06.sys.expression1.apply.op._e_println"));
		put("_e_put",		Outside.service(this,"gus06.sys.expression1.apply.op._e_put"));
		put("_e_put0",		Outside.service(this,"gus06.sys.expression1.apply.op._e_put0"));
		put("_e_put0_ct",	Outside.service(this,"gus06.sys.expression1.apply.op._e_put0_ct"));
		put("_e_put0_ig",	Outside.service(this,"gus06.sys.expression1.apply.op._e_put0_ig"));
		put("_e_put0_ig_d",	Outside.service(this,"gus06.sys.expression1.apply.op._e_put0_ig_d"));
		put("_e_put_count",	Outside.service(this,"gus06.sys.expression1.apply.op._e_put_count"));
		put("_e_put_ct",	Outside.service(this,"gus06.sys.expression1.apply.op._e_put_ct"));
		put("_e_put_ig",	Outside.service(this,"gus06.sys.expression1.apply.op._e_put_ig"));
		put("_e_put_ig_d",	Outside.service(this,"gus06.sys.expression1.apply.op._e_put_ig_d"));
		put("_e_put_inlist",	Outside.service(this,"gus06.sys.expression1.apply.op._e_put_inlist"));
		put("_e_put_inmap_rec",	Outside.service(this,"gus06.sys.expression1.apply.op._e_put_inmap_rec"));
		put("_e_put_inset",	Outside.service(this,"gus06.sys.expression1.apply.op._e_put_inset"));
		put("_e_put_instring",	Outside.service(this,"gus06.sys.expression1.apply.op._e_put_instring"));
		put("_e_put_re",	Outside.service(this,"gus06.sys.expression1.apply.op._e_put_re"));
		put("_e_putall",	Outside.service(this,"gus06.sys.expression1.apply.op._e_putall"));
		put("_e_putall0",	Outside.service(this,"gus06.sys.expression1.apply.op._e_putall0"));
		put("_e_putall0_ct",	Outside.service(this,"gus06.sys.expression1.apply.op._e_putall0_ct"));
		put("_e_putall0_ig",	Outside.service(this,"gus06.sys.expression1.apply.op._e_putall0_ig"));
		put("_e_putall0_ig_d",	Outside.service(this,"gus06.sys.expression1.apply.op._e_putall0_ig_d"));
		put("_e_putall_count",	Outside.service(this,"gus06.sys.expression1.apply.op._e_putall_count"));
		put("_e_putall_ct",	Outside.service(this,"gus06.sys.expression1.apply.op._e_putall_ct"));
		put("_e_putall_ig",	Outside.service(this,"gus06.sys.expression1.apply.op._e_putall_ig"));
		put("_e_putall_ig_d",	Outside.service(this,"gus06.sys.expression1.apply.op._e_putall_ig_d"));
		put("_e_putall_inlist",	Outside.service(this,"gus06.sys.expression1.apply.op._e_putall_inlist"));
		put("_e_putall_inset",	Outside.service(this,"gus06.sys.expression1.apply.op._e_putall_inset"));
		put("_e_putall_instring",Outside.service(this,"gus06.sys.expression1.apply.op._e_putall_instring"));
		put("_e_putnow",	Outside.service(this,"gus06.sys.expression1.apply.op._e_putnow"));
		put("_e_puttoday",	Outside.service(this,"gus06.sys.expression1.apply.op._e_puttoday"));
		put("_e_quickzip",	Outside.service(this,"gus06.sys.expression1.apply.op._e_quickzip"));
		put("_e_quickzip_timestamped",	Outside.service(this,"gus06.sys.expression1.apply.op._e_quickzip_timestamped"));
		put("_e_quickzip_yyyymmdd",	Outside.service(this,"gus06.sys.expression1.apply.op._e_quickzip_yyyymmdd"));
		put("_e_refactorlist1_en",	Outside.service(this,"gus06.sys.expression1.apply.op._e_refactorlist1_en"));
		put("_e_refactorlist1_ig",	Outside.service(this,"gus06.sys.expression1.apply.op._e_refactorlist1_ig"));
		put("_e_refactorlist1_st",	Outside.service(this,"gus06.sys.expression1.apply.op._e_refactorlist1_st"));
		put("_e_refresh",	Outside.service(this,"gus06.sys.expression1.apply.op._e_refresh"));
		put("_e_remove",	Outside.service(this,"gus06.sys.expression1.apply.op._e_remove"));
		put("_e_remove_ct",	Outside.service(this,"gus06.sys.expression1.apply.op._e_remove_ct"));
		put("_e_removeall",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall"));
		put("_e_removeall_co",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_co"));
		put("_e_removeall_co_i",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_co_i"));
		put("_e_removeall_co_n",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_co_n"));
		put("_e_removeall_eq",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_eq"));
		put("_e_removeall_eq_i",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_eq_i"));
		put("_e_removeall_eq_n",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_eq_n"));
		put("_e_removeall_en",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_en"));
		put("_e_removeall_en_i",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_en_i"));
		put("_e_removeall_en_n",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_en_n"));
		put("_e_removeall_empty",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_empty"));
		put("_e_removeall_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_i"));
		put("_e_removeall_k",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_k"));
		put("_e_removeall_kco",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_kco"));
		put("_e_removeall_kco_i",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_kco_i"));
		put("_e_removeall_kco_n",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_kco_n"));
		put("_e_removeall_keq",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_keq"));
		put("_e_removeall_keq_i",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_keq_i"));
		put("_e_removeall_keq_n",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_keq_n"));
		put("_e_removeall_ken",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_ken"));
		put("_e_removeall_ken_i",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_ken_i"));
		put("_e_removeall_ken_n",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_ken_n"));
		put("_e_removeall_kst",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_kst"));
		put("_e_removeall_kst_i",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_kst_i"));
		put("_e_removeall_kst_n",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_kst_n"));
		put("_e_removeall_n",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_n"));
		put("_e_removeall_null",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_null"));
		put("_e_removeall_st",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_st"));
		put("_e_removeall_st_i",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_st_i"));
		put("_e_removeall_st_n",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_st_n"));
		put("_e_removeall_v",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_v"));
		put("_e_removeall_vco",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_vco"));
		put("_e_removeall_vco_i",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_vco_i"));
		put("_e_removeall_vco_n",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_vco_n"));
		put("_e_removeall_veq",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_veq"));
		put("_e_removeall_veq_i",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_veq_i"));
		put("_e_removeall_veq_n",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_veq_n"));
		put("_e_removeall_ven",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_ven"));
		put("_e_removeall_ven_i",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_ven_i"));
		put("_e_removeall_ven_n",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_ven_n"));
		put("_e_removeall_vst",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_vst"));
		put("_e_removeall_vst_i",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_vst_i"));
		put("_e_removeall_vst_n",Outside.service(this,"gus06.sys.expression1.apply.op._e_removeall_vst_n"));
		put("_e_removefirst",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removefirst"));
		put("_e_removeone",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removeone"));
		put("_e_removelast",	Outside.service(this,"gus06.sys.expression1.apply.op._e_removelast"));
		put("_e_renamefile",	Outside.service(this,"gus06.sys.expression1.apply.op._e_renamefile"));
		put("_e_renamefile0",	Outside.service(this,"gus06.sys.expression1.apply.op._e_renamefile0"));
		put("_e_renamefile0_auto",	Outside.service(this,"gus06.sys.expression1.apply.op._e_renamefile0_auto"));
		put("_e_renamefile_auto",	Outside.service(this,"gus06.sys.expression1.apply.op._e_renamefile_auto"));
		put("_e_repaint",		Outside.service(this,"gus06.sys.expression1.apply.op._e_repaint"));
		put("_e_replace1",		Outside.service(this,"gus06.sys.expression1.apply.op._e_replace1"));
		put("_e_replace1_end",		Outside.service(this,"gus06.sys.expression1.apply.op._e_replace1_end"));
		put("_e_replace1_end_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_replace1_end_i"));
		put("_e_replace1_first",	Outside.service(this,"gus06.sys.expression1.apply.op._e_replace1_first"));
		put("_e_replace1_first_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_replace1_first_i"));
		put("_e_replace1_i",		Outside.service(this,"gus06.sys.expression1.apply.op._e_replace1_i"));
		put("_e_replace1_last",		Outside.service(this,"gus06.sys.expression1.apply.op._e_replace1_last"));
		put("_e_replace1_last_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_replace1_last_i"));
		put("_e_replace1_smart",	Outside.service(this,"gus06.sys.expression1.apply.op._e_replace1_smart"));
		put("_e_replace1_start",	Outside.service(this,"gus06.sys.expression1.apply.op._e_replace1_start"));
		put("_e_replace1_start_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_replace1_start_i"));
		put("_e_replaceall",		Outside.service(this,"gus06.sys.expression1.apply.op._e_replaceall"));
		put("_e_restorefile",		Outside.service(this,"gus06.sys.expression1.apply.op._e_restorefile"));
		put("_e_restorefile_choose",	Outside.service(this,"gus06.sys.expression1.apply.op._e_restorefile_choose"));
		put("_e_restorefile_last",	Outside.service(this,"gus06.sys.expression1.apply.op._e_restorefile_last"));
		put("_e_reverse",	Outside.service(this,"gus06.sys.expression1.apply.op._e_reverse"));
		put("_e_shuffle",	Outside.service(this,"gus06.sys.expression1.apply.op._e_shuffle"));
		put("_e_sort",		Outside.service(this,"gus06.sys.expression1.apply.op._e_sort"));
		put("_e_sort_inv",	Outside.service(this,"gus06.sys.expression1.apply.op._e_sort_inv"));
		put("_e_sortby",	Outside.service(this,"gus06.sys.expression1.apply.op._e_sortby"));
		put("_e_sortby_inv",	Outside.service(this,"gus06.sys.expression1.apply.op._e_sortby_inv"));
		put("_e_sortnum",	Outside.service(this,"gus06.sys.expression1.apply.op._e_sortnum"));
		put("_e_sortnum_inv",	Outside.service(this,"gus06.sys.expression1.apply.op._e_sortnum_inv"));
		put("_e_sortstr",	Outside.service(this,"gus06.sys.expression1.apply.op._e_sortstr"));
		put("_e_sortstr_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_sortstr_i"));
		put("_e_sortstr_inv",	Outside.service(this,"gus06.sys.expression1.apply.op._e_sortstr_inv"));
		put("_e_sortstr_inv_i",	Outside.service(this,"gus06.sys.expression1.apply.op._e_sortstr_inv_i"));
		put("_e_sortwith",	Outside.service(this,"gus06.sys.expression1.apply.op._e_sortwith"));
		put("_e_sortwith_inv",	Outside.service(this,"gus06.sys.expression1.apply.op._e_sortwith_inv"));
		put("_e_sub",		Outside.service(this,"gus06.sys.expression1.apply.op._e_sub"));
		put("_e_sub0",		Outside.service(this,"gus06.sys.expression1.apply.op._e_sub0"));
		put("_e_swap",		Outside.service(this,"gus06.sys.expression1.apply.op._e_swap"));
		put("_e_swap_random",	Outside.service(this,"gus06.sys.expression1.apply.op._e_swap_random"));
		put("_e_syndir",	Outside.service(this,"gus06.sys.expression1.apply.op._e_syndir"));
		put("_e_sysprint",	Outside.service(this,"gus06.sys.expression1.apply.op._e_sysprint"));
		put("_e_sysprintln",	Outside.service(this,"gus06.sys.expression1.apply.op._e_sysprintln"));
		put("_e_throw",		Outside.service(this,"gus06.sys.expression1.apply.op._e_throw"));
		put("_e_throw_onempty",	Outside.service(this,"gus06.sys.expression1.apply.op._e_throw_onempty"));
		put("_e_throw_onfalse",	Outside.service(this,"gus06.sys.expression1.apply.op._e_throw_onfalse"));
		put("_e_throw_onmany",	Outside.service(this,"gus06.sys.expression1.apply.op._e_throw_onmany"));
		put("_e_throw_onnempty",Outside.service(this,"gus06.sys.expression1.apply.op._e_throw_onnempty"));
		put("_e_throw_onnnull",	Outside.service(this,"gus06.sys.expression1.apply.op._e_throw_onnnull"));
		put("_e_throw_onnull",	Outside.service(this,"gus06.sys.expression1.apply.op._e_throw_onnull"));
		put("_e_throw_ontrue",	Outside.service(this,"gus06.sys.expression1.apply.op._e_throw_ontrue"));
		put("_e_throw_runtime",	Outside.service(this,"gus06.sys.expression1.apply.op._e_throw_runtime"));
		put("_e_transparent",	Outside.service(this,"gus06.sys.expression1.apply.op._e_transparent"));
		put("_e_treecomplete1",	Outside.service(this,"gus06.sys.expression1.apply.op._e_treecomplete1"));
		put("_e_treecomplete2",	Outside.service(this,"gus06.sys.expression1.apply.op._e_treecomplete2"));
		put("_e_truncate",	Outside.service(this,"gus06.sys.expression1.apply.op._e_truncate"));
		put("_e_typekey",	Outside.service(this,"gus06.sys.expression1.apply.op._e_typekey"));
		put("_e_typetext",	Outside.service(this,"gus06.sys.expression1.apply.op._e_typetext"));
		put("_e_unrar",		Outside.service(this,"gus06.sys.expression1.apply.op._e_unrar"));
		put("_e_unzip",		Outside.service(this,"gus06.sys.expression1.apply.op._e_unzip"));
		put("_e_unzip_location",	Outside.service(this,"gus06.sys.expression1.apply.op._e_unzip_location"));
		put("_e_unzip_location2",	Outside.service(this,"gus06.sys.expression1.apply.op._e_unzip_location2"));
		put("_e_write_fromclipboard",	Outside.service(this,"gus06.sys.expression1.apply.op._e_write_fromclipboard"));
		put("_e_zip",		Outside.service(this,"gus06.sys.expression1.apply.op._e_zip"));
		put("_ebook_cover",	Outside.service(this,"gus06.sys.expression1.apply.op._ebook_cover"));
		put("_ebook_isbn",	Outside.service(this,"gus06.sys.expression1.apply.op._ebook_isbn"));
		put("_ebook_prop",	Outside.service(this,"gus06.sys.expression1.apply.op._ebook_prop"));
		put("_ee1",		Outside.service(this,"gus06.sys.expression1.apply.op._ee1"));
		put("_ee2",		Outside.service(this,"gus06.sys.expression1.apply.op._ee2"));
		put("_ee3",		Outside.service(this,"gus06.sys.expression1.apply.op._ee3"));
		put("_empty",		Outside.service(this,"gus06.sys.expression1.apply.op._empty"));
		put("_en",		Outside.service(this,"gus06.sys.expression1.apply.op._en"));
		put("_en_blank",	Outside.service(this,"gus06.sys.expression1.apply.op._en_blank"));
		put("_en_digit",	Outside.service(this,"gus06.sys.expression1.apply.op._en_digit"));
		put("_en_i",		Outside.service(this,"gus06.sys.expression1.apply.op._en_i"));
		put("_en_letter",	Outside.service(this,"gus06.sys.expression1.apply.op._en_letter"));
		put("_en_lower",	Outside.service(this,"gus06.sys.expression1.apply.op._en_lower"));
		put("_en_n",		Outside.service(this,"gus06.sys.expression1.apply.op._en_n"));
		put("_en_oneofthem",	Outside.service(this,"gus06.sys.expression1.apply.op._en_oneofthem"));
		put("_en_oneofthem_i",	Outside.service(this,"gus06.sys.expression1.apply.op._en_oneofthem_i"));
		put("_en_oneofthem_n",	Outside.service(this,"gus06.sys.expression1.apply.op._en_oneofthem_n"));
		put("_en_punct",	Outside.service(this,"gus06.sys.expression1.apply.op._en_punct"));
		put("_en_regex",	Outside.service(this,"gus06.sys.expression1.apply.op._en_regex"));
		put("_en_s",		Outside.service(this,"gus06.sys.expression1.apply.op._en_s"));
		put("_en_si",		Outside.service(this,"gus06.sys.expression1.apply.op._en_si"));
		put("_en_sn",		Outside.service(this,"gus06.sys.expression1.apply.op._en_sn"));
		put("_en_upper",	Outside.service(this,"gus06.sys.expression1.apply.op._en_upper"));
		put("_encode_datastring",Outside.service(this,"gus06.sys.expression1.apply.op._encode_datastring"));
		put("_encode_forbidden",Outside.service(this,"gus06.sys.expression1.apply.op._encode_forbidden"));
		put("_encode_hill",	Outside.service(this,"gus06.sys.expression1.apply.op._encode_hill"));
		put("_encode_url",	Outside.service(this,"gus06.sys.expression1.apply.op._encode_url"));
		put("_encode_uu",	Outside.service(this,"gus06.sys.expression1.apply.op._encode_uu"));
		put("_entities",	Outside.service(this,"gus06.sys.expression1.apply.op._entities"));
		put("_entities_co",	Outside.service(this,"gus06.sys.expression1.apply.op._entities_co"));
		put("_entities_en",	Outside.service(this,"gus06.sys.expression1.apply.op._entities_en"));
		put("_entities_st",	Outside.service(this,"gus06.sys.expression1.apply.op._entities_st"));
		put("_entity_doc",	Outside.service(this,"gus06.sys.expression1.apply.op._entity_doc"));
		put("_entity_new",	Outside.service(this,"gus06.sys.expression1.apply.op._entity_new"));
		put("_entity_src",	Outside.service(this,"gus06.sys.expression1.apply.op._entity_src"));
		put("_entity_unique",	Outside.service(this,"gus06.sys.expression1.apply.op._entity_unique"));
		put("_entitysrc_date",		Outside.service(this,"gus06.sys.expression1.apply.op._entitysrc_date"));
		put("_entitysrc_infomap",	Outside.service(this,"gus06.sys.expression1.apply.op._entitysrc_infomap"));
		put("_entitysrc_name",		Outside.service(this,"gus06.sys.expression1.apply.op._entitysrc_name"));
		put("_env_cmds",	Outside.service(this,"gus06.sys.expression1.apply.op._env_cmds"));
		put("_env_paths",	Outside.service(this,"gus06.sys.expression1.apply.op._env_paths"));
		put("_env_userhome",	Outside.service(this,"gus06.sys.expression1.apply.op._env_userhome"));
		put("_epub_cover",	Outside.service(this,"gus06.sys.expression1.apply.op._epub_cover"));
		put("_epub_prop",	Outside.service(this,"gus06.sys.expression1.apply.op._epub_prop"));
		put("_eq",		Outside.service(this,"gus06.sys.expression1.apply.op._eq"));
		put("_eq_i",		Outside.service(this,"gus06.sys.expression1.apply.op._eq_i"));
		put("_eq_n",		Outside.service(this,"gus06.sys.expression1.apply.op._eq_n"));
		put("_eq_oneofthem",	Outside.service(this,"gus06.sys.expression1.apply.op._eq_oneofthem"));
		put("_eq_oneofthem_i",	Outside.service(this,"gus06.sys.expression1.apply.op._eq_oneofthem_i"));
		put("_eq_oneofthem_n",	Outside.service(this,"gus06.sys.expression1.apply.op._eq_oneofthem_n"));
		put("_eq_s",		Outside.service(this,"gus06.sys.expression1.apply.op._eq_s"));
		put("_eq_si",		Outside.service(this,"gus06.sys.expression1.apply.op._eq_si"));
		put("_eq_sn",		Outside.service(this,"gus06.sys.expression1.apply.op._eq_sn"));
		put("_errorstream",	Outside.service(this,"gus06.sys.expression1.apply.op._errorstream"));
		put("_escap_meta",	Outside.service(this,"gus06.sys.expression1.apply.op._escap_meta"));
		put("_even",		Outside.service(this,"gus06.sys.expression1.apply.op._even"));
		put("_excludeall",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall"));
		put("_excludeall_co",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_co"));
		put("_excludeall_co_i",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_co_i"));
		put("_excludeall_co_n",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_co_n"));
		put("_excludeall_co_regex",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_co_regex"));
		put("_excludeall_empty",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_empty"));
		put("_excludeall_en",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_en"));
		put("_excludeall_en_i",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_en_i"));
		put("_excludeall_en_n",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_en_n"));
		put("_excludeall_eq",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_eq"));
		put("_excludeall_eq_i",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_eq_i"));
		put("_excludeall_eq_n",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_eq_n"));
		put("_excludeall_i",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_i"));
		put("_excludeall_k",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_k"));
		put("_excludeall_kco",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_kco"));
		put("_excludeall_kco_i",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_kco_i"));
		put("_excludeall_kco_n",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_kco_n"));
		put("_excludeall_keq",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_keq"));
		put("_excludeall_keq_i",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_keq_i"));
		put("_excludeall_keq_n",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_keq_n"));
		put("_excludeall_ken",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_ken"));
		put("_excludeall_ken_i",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_ken_i"));
		put("_excludeall_ken_n",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_ken_n"));
		put("_excludeall_kst",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_kst"));
		put("_excludeall_kst_i",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_kst_i"));
		put("_excludeall_kst_n",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_kst_n"));
		put("_excludeall_n",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_n"));
		put("_excludeall_null",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_null"));
		put("_excludeall_st",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_st"));
		put("_excludeall_st_i",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_st_i"));
		put("_excludeall_st_n",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_st_n"));
		put("_excludeall_v",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_v"));
		put("_excludeall_vco",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_vco"));
		put("_excludeall_vco_i",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_vco_i"));
		put("_excludeall_vco_n",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_vco_n"));
		put("_excludeall_veq",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_veq"));
		put("_excludeall_veq_i",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_veq_i"));
		put("_excludeall_veq_n",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_veq_n"));
		put("_excludeall_ven",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_ven"));
		put("_excludeall_ven_i",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_ven_i"));
		put("_excludeall_ven_n",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_ven_n"));
		put("_excludeall_vst",	Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_vst"));
		put("_excludeall_vst_i",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_vst_i"));
		put("_excludeall_vst_n",Outside.service(this,"gus06.sys.expression1.apply.op._excludeall_vst_n"));
		put("_excludelines",		Outside.service(this,"gus06.sys.expression1.apply.op._excludelines"));
		put("_excludelines_blank",	Outside.service(this,"gus06.sys.expression1.apply.op._excludelines_blank"));
		put("_excludelines_co",		Outside.service(this,"gus06.sys.expression1.apply.op._excludelines_co"));
		put("_excludelines_co_i",	Outside.service(this,"gus06.sys.expression1.apply.op._excludelines_co_i"));
		put("_excludelines_co_n",	Outside.service(this,"gus06.sys.expression1.apply.op._excludelines_co_n"));
		put("_excludelines_co_regex",	Outside.service(this,"gus06.sys.expression1.apply.op._excludelines_co_regex"));
		put("_excludelines_eq",		Outside.service(this,"gus06.sys.expression1.apply.op._excludelines_eq"));
		put("_excludelines_eq_i",	Outside.service(this,"gus06.sys.expression1.apply.op._excludelines_eq_i"));
		put("_excludelines_eq_n",	Outside.service(this,"gus06.sys.expression1.apply.op._excludelines_eq_n"));
		put("_excludelines_en",		Outside.service(this,"gus06.sys.expression1.apply.op._excludelines_en"));
		put("_excludelines_en_i",	Outside.service(this,"gus06.sys.expression1.apply.op._excludelines_en_i"));
		put("_excludelines_en_n",	Outside.service(this,"gus06.sys.expression1.apply.op._excludelines_en_n"));
		put("_excludelines_st",		Outside.service(this,"gus06.sys.expression1.apply.op._excludelines_st"));
		put("_excludelines_st_i",	Outside.service(this,"gus06.sys.expression1.apply.op._excludelines_st_i"));
		put("_excludelines_st_n",	Outside.service(this,"gus06.sys.expression1.apply.op._excludelines_st_n"));
		put("_exec",		Outside.service(this,"gus06.sys.expression1.apply.op._exec"));
		put("_exec_tostring",	Outside.service(this,"gus06.sys.expression1.apply.op._exec_tostring"));
		put("_exec_toutf8",	Outside.service(this,"gus06.sys.expression1.apply.op._exec_toutf8"));
		put("_executable",	Outside.service(this,"gus06.sys.expression1.apply.op._executable"));
		put("_execute",		Outside.service(this,"gus06.sys.expression1.apply.op._execute"));
		put("_executor",	Outside.service(this,"gus06.sys.expression1.apply.op._executor"));
		put("_exists",		Outside.service(this,"gus06.sys.expression1.apply.op._exists"));
		put("_exit",		Outside.service(this,"gus06.sys.expression1.apply.op._exit"));
		put("_exp",		Outside.service(this,"gus06.sys.expression1.apply.op._exp"));
		put("_ext",		Outside.service(this,"gus06.sys.expression1.apply.op._ext"));
		put("_ext_to_mime",	Outside.service(this,"gus06.sys.expression1.apply.op._ext_to_mime"));
		put("_ext_to_mimehier",	Outside.service(this,"gus06.sys.expression1.apply.op._ext_to_mimehier"));
		put("_extend_east",	Outside.service(this,"gus06.sys.expression1.apply.op._extend_east"));
		put("_extend_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extend_f"));
		put("_extend_g",	Outside.service(this,"gus06.sys.expression1.apply.op._extend_g"));
		put("_extend_i",	Outside.service(this,"gus06.sys.expression1.apply.op._extend_i"));
		put("_extend_north",	Outside.service(this,"gus06.sys.expression1.apply.op._extend_north"));
		put("_extend_p",	Outside.service(this,"gus06.sys.expression1.apply.op._extend_p"));
		put("_extend_r",	Outside.service(this,"gus06.sys.expression1.apply.op._extend_r"));
		put("_extend_south",	Outside.service(this,"gus06.sys.expression1.apply.op._extend_south"));
		put("_extend_t1",	Outside.service(this,"gus06.sys.expression1.apply.op._extend_t1"));
		put("_extend_t2",	Outside.service(this,"gus06.sys.expression1.apply.op._extend_t2"));
		put("_extend_v",	Outside.service(this,"gus06.sys.expression1.apply.op._extend_v"));
		put("_extend_west",	Outside.service(this,"gus06.sys.expression1.apply.op._extend_west"));
		put("_extract1f_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract1f_a"));
		put("_extract1f_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract1f_f"));
		put("_extract1f_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract1f_k"));
		put("_extract1f_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract1f_l"));
		put("_extract1s_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract1s_a"));
		put("_extract1s_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract1s_f"));
		put("_extract1s_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract1s_k"));
		put("_extract1s_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract1s_l"));
		put("_extract2f_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract2f_a"));
		put("_extract2f_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract2f_f"));
		put("_extract2f_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract2f_k"));
		put("_extract2f_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract2f_l"));
		put("_extract2s_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract2s_a"));
		put("_extract2s_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract2s_f"));
		put("_extract2s_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract2s_k"));
		put("_extract2s_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract2s_l"));
		put("_extract_alphanum_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_alphanum_a"));
		put("_extract_alphanum_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_alphanum_f"));
		put("_extract_alphanum_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_alphanum_k"));
		put("_extract_alphanum_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_alphanum_l"));
		put("_extract_alphanum1_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_alphanum1_a"));
		put("_extract_alphanum1_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_alphanum1_f"));
		put("_extract_alphanum1_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_alphanum1_k"));
		put("_extract_alphanum1_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_alphanum1_l"));
		put("_extract_angle_a",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_angle_a"));
		put("_extract_angle_f",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_angle_f"));
		put("_extract_angle_k",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_angle_k"));
		put("_extract_angle_l",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_angle_l"));
		put("_extract_curly_a",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_curly_a"));
		put("_extract_curly_f",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_curly_f"));
		put("_extract_curly_k",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_curly_k"));
		put("_extract_curly_l",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_curly_l"));
		put("_extract_date_en_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_date_en_a"));
		put("_extract_date_en_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_date_en_f"));
		put("_extract_date_en_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_date_en_l"));
		put("_extract_date_fr_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_date_fr_a"));
		put("_extract_date_fr_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_date_fr_f"));
		put("_extract_date_fr_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_date_fr_l"));
		put("_extract_email_a",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_email_a"));
		put("_extract_email_f",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_email_f"));
		put("_extract_email_k",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_email_k"));
		put("_extract_email_l",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_email_l"));
		put("_extract_hexa_a",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_hexa_a"));
		put("_extract_hexa_f",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_hexa_f"));
		put("_extract_hexa_k",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_hexa_k"));
		put("_extract_hexa_l",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_hexa_l"));
		put("_extract_html_a_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_a_a"));
		put("_extract_html_a_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_a_f"));
		put("_extract_html_a_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_a_k"));
		put("_extract_html_a_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_a_l"));
		put("_extract_html_body_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_body_f"));
		put("_extract_html_body_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_body_k"));
		put("_extract_html_classes",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_classes"));
		put("_extract_html_form_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_form_a"));
		put("_extract_html_form_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_form_f"));
		put("_extract_html_form_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_form_k"));
		put("_extract_html_form_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_form_l"));
		put("_extract_html_h1_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_h1_a"));
		put("_extract_html_h1_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_h1_f"));
		put("_extract_html_h1_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_h1_k"));
		put("_extract_html_h1_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_h1_l"));
		put("_extract_html_h2_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_h2_a"));
		put("_extract_html_h2_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_h2_f"));
		put("_extract_html_h2_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_h2_k"));
		put("_extract_html_h2_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_h2_l"));
		put("_extract_html_h3_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_h3_a"));
		put("_extract_html_h3_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_h3_f"));
		put("_extract_html_h3_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_h3_k"));
		put("_extract_html_h3_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_h3_l"));
		put("_extract_html_head_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_head_f"));
		put("_extract_html_head_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_head_k"));
		put("_extract_html_href_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_href_a"));
		put("_extract_html_ids",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_ids"));
		put("_extract_html_img_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_img_a"));
		put("_extract_html_img_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_img_f"));
		put("_extract_html_img_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_img_k"));
		put("_extract_html_img_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_img_l"));
		put("_extract_html_input_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_input_a"));
		put("_extract_html_input_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_input_f"));
		put("_extract_html_input_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_input_k"));
		put("_extract_html_input_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_input_l"));
		put("_extract_html_li_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_li_a"));
		put("_extract_html_li_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_li_f"));
		put("_extract_html_li_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_li_k"));
		put("_extract_html_li_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_li_l"));
		put("_extract_html_link_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_link_a"));
		put("_extract_html_link_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_link_f"));
		put("_extract_html_link_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_link_k"));
		put("_extract_html_link_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_link_l"));
		put("_extract_html_meta_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_meta_a"));
		put("_extract_html_meta_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_meta_f"));
		put("_extract_html_meta_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_meta_k"));
		put("_extract_html_meta_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_meta_l"));
		put("_extract_html_script_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_script_a"));
		put("_extract_html_script_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_script_f"));
		put("_extract_html_script_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_script_k"));
		put("_extract_html_script_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_script_l"));
		put("_extract_html_span_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_span_a"));
		put("_extract_html_span_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_span_f"));
		put("_extract_html_span_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_span_k"));
		put("_extract_html_span_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_span_l"));
		put("_extract_html_src_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_src_a"));
		put("_extract_html_style_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_style_a"));
		put("_extract_html_style_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_style_f"));
		put("_extract_html_style_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_style_k"));
		put("_extract_html_style_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_style_l"));
		put("_extract_html_table_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_table_a"));
		put("_extract_html_table_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_table_f"));
		put("_extract_html_table_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_table_k"));
		put("_extract_html_table_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_table_l"));
		put("_extract_html_td_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_td_a"));
		put("_extract_html_td_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_td_f"));
		put("_extract_html_td_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_td_k"));
		put("_extract_html_td_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_td_l"));
		put("_extract_html_textarea_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_textarea_a"));
		put("_extract_html_textarea_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_textarea_f"));
		put("_extract_html_textarea_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_textarea_k"));
		put("_extract_html_textarea_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_textarea_l"));
		put("_extract_html_th_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_th_a"));
		put("_extract_html_th_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_th_f"));
		put("_extract_html_th_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_th_k"));
		put("_extract_html_th_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_th_l"));
		put("_extract_html_title_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_title_f"));
		put("_extract_html_title_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_title_k"));
		put("_extract_html_tr_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_tr_a"));
		put("_extract_html_tr_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_tr_f"));
		put("_extract_html_tr_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_tr_k"));
		put("_extract_html_tr_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_tr_l"));
		put("_extract_html_ul_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_ul_a"));
		put("_extract_html_ul_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_ul_f"));
		put("_extract_html_ul_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_ul_k"));
		put("_extract_html_ul_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_html_ul_l"));
		put("_extract_htmlblock_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_htmlblock_a"));
		put("_extract_htmlblock_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_htmlblock_f"));
		put("_extract_htmlblock_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_htmlblock_l"));
		put("_extract_htmltag_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_htmltag_a"));
		put("_extract_htmltag_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_htmltag_f"));
		put("_extract_htmltag_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_htmltag_l"));
		put("_extract_in_angle_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_angle_a"));
		put("_extract_in_angle_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_angle_f"));
		put("_extract_in_angle_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_angle_k"));
		put("_extract_in_angle_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_angle_l"));
		put("_extract_in_curly_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_curly_a"));
		put("_extract_in_curly_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_curly_f"));
		put("_extract_in_curly_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_curly_k"));
		put("_extract_in_curly_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_curly_l"));
		put("_extract_in_htmlblock_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_htmlblock_a"));
		put("_extract_in_htmlblock_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_htmlblock_f"));
		put("_extract_in_htmlblock_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_htmlblock_k"));
		put("_extract_in_htmlblock_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_htmlblock_l"));
		put("_extract_in_parenthesis_a",Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_parenthesis_a"));
		put("_extract_in_parenthesis_f",Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_parenthesis_f"));
		put("_extract_in_parenthesis_k",Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_parenthesis_k"));
		put("_extract_in_parenthesis_l",Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_parenthesis_l"));
		put("_extract_in_quote2_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_quote2_a"));
		put("_extract_in_quote2_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_quote2_f"));
		put("_extract_in_quote2_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_quote2_k"));
		put("_extract_in_quote2_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_quote2_l"));
		put("_extract_in_quote_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_quote_a"));
		put("_extract_in_quote_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_quote_f"));
		put("_extract_in_quote_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_quote_k"));
		put("_extract_in_quote_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_quote_l"));
		put("_extract_in_square_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_square_a"));
		put("_extract_in_square_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_square_f"));
		put("_extract_in_square_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_square_k"));
		put("_extract_in_square_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_in_square_l"));
		put("_extract_lower_a",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_lower_a"));
		put("_extract_lower_f",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_lower_f"));
		put("_extract_lower_k",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_lower_k"));
		put("_extract_lower_l",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_lower_l"));
		put("_extract_number_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_number_a"));
		put("_extract_number_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_number_f"));
		put("_extract_number_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_number_k"));
		put("_extract_number_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_number_l"));
		put("_extract_parenthesis_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_parenthesis_a"));
		put("_extract_parenthesis_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_parenthesis_f"));
		put("_extract_parenthesis_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_parenthesis_k"));
		put("_extract_parenthesis_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_parenthesis_l"));
		put("_extract_quote2_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_quote2_a"));
		put("_extract_quote2_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_quote2_f"));
		put("_extract_quote2_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_quote2_k"));
		put("_extract_quote2_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_quote2_l"));
		put("_extract_quote_a",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_quote_a"));
		put("_extract_quote_f",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_quote_f"));
		put("_extract_quote_k",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_quote_k"));
		put("_extract_quote_l",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_quote_l"));
		put("_extract_regex_1_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_regex_1_a"));
		put("_extract_regex_1_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_regex_1_f"));
		put("_extract_regex_1_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_regex_1_k"));
		put("_extract_regex_1_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_regex_1_l"));
		put("_extract_regex_a",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_regex_a"));
		put("_extract_regex_f",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_regex_f"));
		put("_extract_regex_k",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_regex_k"));
		put("_extract_regex_l",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_regex_l"));
		put("_extract_square_a",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_square_a"));
		put("_extract_square_f",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_square_f"));
		put("_extract_square_k",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_square_k"));
		put("_extract_square_l",	Outside.service(this,"gus06.sys.expression1.apply.op._extract_square_l"));
		put("_extract_tag_a",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_tag_a"));
		put("_extract_tag_f",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_tag_f"));
		put("_extract_tag_k",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_tag_k"));
		put("_extract_tag_l",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_tag_l"));
		put("_extract_upper_a",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_upper_a"));
		put("_extract_upper_f",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_upper_f"));
		put("_extract_upper_k",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_upper_k"));
		put("_extract_upper_l",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_upper_l"));
		put("_extract_url_a",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_url_a"));
		put("_extract_url_f",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_url_f"));
		put("_extract_url_k",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_url_k"));
		put("_extract_url_l",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_url_l"));
		put("_extract_word_a",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_word_a"));
		put("_extract_word_f",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_word_f"));
		put("_extract_word_k",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_word_k"));
		put("_extract_word_l",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_word_l"));
		put("_extract_year_a",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_year_a"));
		put("_extract_year_f",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_year_f"));
		put("_extract_year_k",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_year_k"));
		put("_extract_year_l",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_year_l"));
		put("_extract_yearp_a",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_yearp_a"));
		put("_extract_yearp_f",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_yearp_f"));
		put("_extract_yearp_k",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_yearp_k"));
		put("_extract_yearp_l",		Outside.service(this,"gus06.sys.expression1.apply.op._extract_yearp_l"));
		put("_extractline_co",		Outside.service(this,"gus06.sys.expression1.apply.op._extractline_co"));
		put("_extractline_co_i",	Outside.service(this,"gus06.sys.expression1.apply.op._extractline_co_i"));
		put("_extractline_en",		Outside.service(this,"gus06.sys.expression1.apply.op._extractline_en"));
		put("_extractline_en_i",	Outside.service(this,"gus06.sys.expression1.apply.op._extractline_en_i"));
		put("_extractline_st",		Outside.service(this,"gus06.sys.expression1.apply.op._extractline_st"));
		put("_extractline_st_i",	Outside.service(this,"gus06.sys.expression1.apply.op._extractline_st_i"));
		put("_extractlinks",		Outside.service(this,"gus06.sys.expression1.apply.op._extractlinks"));
		put("_extractlinks_ext",	Outside.service(this,"gus06.sys.expression1.apply.op._extractlinks_ext"));
		put("_extractlinks_ext_href",	Outside.service(this,"gus06.sys.expression1.apply.op._extractlinks_ext_href"));
		put("_extractlinks_ext_src",	Outside.service(this,"gus06.sys.expression1.apply.op._extractlinks_ext_src"));
		put("_extractlinks_href",	Outside.service(this,"gus06.sys.expression1.apply.op._extractlinks_href"));
		put("_extractlinks_int",	Outside.service(this,"gus06.sys.expression1.apply.op._extractlinks_int"));
		put("_extractlinks_int_href",	Outside.service(this,"gus06.sys.expression1.apply.op._extractlinks_int_href"));
		put("_extractlinks_int_src",	Outside.service(this,"gus06.sys.expression1.apply.op._extractlinks_int_src"));
		put("_extractlinks_src",	Outside.service(this,"gus06.sys.expression1.apply.op._extractlinks_src"));
		put("_extractor1",		Outside.service(this,"gus06.sys.expression1.apply.op._extractor1"));
	}
	
	
	private void put(String name, Service s) throws Exception
	{
		if(map.containsKey(name)) throw new Exception("Operator name already registered: "+name);
		map.put(name,s);
	}
	
	
	public Object g() throws Exception
	{return map;}
}