package a.entity.gus06.sys.geomap1.fr.departments.gui1;

import java.util.HashMap;
import java.util.Map;

public class UtilDepartment {

	public static Map<String, String> DEPARTMENTS = new HashMap<String,String>() {
		private static final long serialVersionUID = 1L;

		{
			put("01", "Ain");
			put("02", "Aisne");
			put("03", "Allier");
			put("04", "Alpes-de-Haute-Provence");
			put("05", "Hautes-Alpes");
			put("06", "Alpes-Maritimes");
			put("07", "Ard�che");
			put("08", "Ardennes");
			put("09", "Ari�ge");
			put("10", "Aube");
			put("11", "Aude");
			put("12", "Aveyron");
			put("13", "Bouches-du-Rh�ne");
			put("14", "Calvados");
			put("15", "Cantal");
			put("16", "Charente");
			put("17", "Charente-Maritime");
			put("18", "Cher");
			put("19", "Corr�ze");
			put("2A", "Corse-du-Sud");
			put("2B", "Haute-Corse");
			put("21", "C�te-d'Or");
			put("22", "C�tes-d'Armor");
			put("23", "Creuse");
			put("24", "Dordogne");
			put("25", "Doubs");
			put("26", "Dr�me");
			put("27", "Eure");
			put("28", "Eure-et-Loir");
			put("29", "Finist�re");
			put("30", "Gard");
			put("31", "Haute-Garonne");
			put("32", "Gers");
			put("33", "Gironde");
			put("34", "H�rault");
			put("35", "Ille-et-Vilaine");
			put("36", "Indre");
			put("37", "Indre-et-Loire");
			put("38", "Is�re");
			put("39", "Jura");
			put("40", "Landes");
			put("41", "Loir-et-Cher");
			put("42", "Loire");
			put("43", "Haute-Loire");
			put("44", "Loire-Atlantique");
			put("45", "Loiret");
			put("46", "Lot");
			put("47", "Lot-et-Garonne");
			put("48", "Loz�re");
			put("49", "Maine-et-Loire");
			put("50", "Manche");
			put("51", "Marne");
			put("52", "Haute-Marne");
			put("53", "Mayenne");
			put("54", "Meurthe-et-Moselle");
			put("55", "Meuse");
			put("56", "Morbihan");
			put("57", "Moselle");
			put("58", "Ni�vre");
			put("59", "Nord");
			put("60", "Oise");
			put("61", "Orne");
			put("62", "Pas-de-Calais");
			put("63", "Puy-de-D�me");
			put("64", "Pyr�n�es-Atlantiques");
			put("65", "Hautes-Pyr�n�es");
			put("66", "Pyr�n�es-Orientales");
			put("67", "Bas-Rhin");
			put("68", "Haut-Rhin");
			put("69", "Rh�ne");
			put("70", "Haute-Sa�ne");
			put("71", "Sa�ne-et-Loire");
			put("72", "Sarthe");
			put("73", "Savoie");
			put("74", "Haute-Savoie");
			put("75", "Paris");
			put("76", "Seine-Maritime");
			put("77", "Seine-et-Marne");
			put("78", "Yvelines");
			put("79", "Deux-S�vres");
			put("80", "Somme");
			put("81", "Tarn");
			put("82", "Tarn-et-Garonne");
			put("83", "Var");
			put("84", "Vaucluse");
			put("85", "Vend�e");
			put("86", "Vienne");
			put("87", "Haute-Vienne");
			put("88", "Vosges");
			put("89", "Yonne");
			put("90", "Territoire de Belfort");
			put("91", "Essonne");
			put("92", "Hauts-de-Seine");
			put("93", "Seine-Saint-Denis");
			put("94", "Val-de-Marne");
			put("95", "Val-d'Oise");
		}
	};
}
